services:
    ubuntu:
        public: true
        container_name: tzchz
        image: consol/ubuntu-xfce-vnc:latest
        ports:
            - 6080:6080
        environment: 
            - VNC_PASSWD=tzchz
            - GEOMETRY=1280x768
            - TZ=Asia/Shanghai
            - DEPTH=24
        volumes: 
            - /root/Desktop
            - /home
        resources:
          cpu: 1000m
          memory: 3072Mi
          storage:
            size: 5Gi
            class: standard
